"""Add folder_id to public_links

Revision ID: 8ff15344eecb
Revises: 95be5ffd94ba
Create Date: 2026-03-10 20:43:26.344689

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff15344eecb'
down_revision: str | Sequence[str] | None = '95be5ffd94ba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_links', sa.Column('folder_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'public_links', 'folders', ['folder_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'public_links', type_='foreignkey')
    op.drop_column('public_links', 'folder_id')
    # ### end Alembic commands ###
