"""Add path to files

Revision ID: 95be5ffd94ba
Revises: 4f9e2a95d3f0
Create Date: 2026-03-10 12:24:07.827339

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95be5ffd94ba'
down_revision: str | Sequence[str] | None = '4f9e2a95d3f0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'path')
    # ### end Alembic commands ###
