"""fix_folder_id_nullable

Revision ID: aa79ea6388f8
Revises: e3cac20653b2
Create Date: 2026-03-28 20:31:42.305778

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa79ea6388f8'
down_revision: str | Sequence[str] | None = 'e3cac20653b2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'folder_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'folder_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
