"""Make file_id and folder_id optional

Revision ID: 73dd4fe22fce
Revises: 8ff15344eecb
Create Date: 2026-03-10 20:50:12.137327

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73dd4fe22fce'
down_revision: str | Sequence[str] | None = '8ff15344eecb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('public_links', 'file_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('public_links', 'folder_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('public_links', 'folder_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('public_links', 'file_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
