"""Make folder_id optional in minio_sessions

Revision ID: e3cac20653b2
Revises: 73dd4fe22fce
Create Date: 2026-03-10 22:00:49.250494

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3cac20653b2'
down_revision: str | Sequence[str] | None = '73dd4fe22fce'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('minio_sessions', 'folder_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('minio_sessions', 'folder_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
